// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OData_Learning.DAL;

#nullable disable

namespace OData_Learning.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OData_Learning.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "First"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Second"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Third"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fourth"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fifth"
                        });
                });

            modelBuilder.Entity("OData_Learning.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "rauf.salahov@example.com",
                            FirstName = "Rauf",
                            GradeId = 1,
                            LastName = "Salahov"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "zahra.nabiyeva@example.com",
                            FirstName = "Zahra",
                            GradeId = 2,
                            LastName = "Nabiyeva"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "emil.musayev@example.com",
                            FirstName = "Emil",
                            GradeId = 3,
                            LastName = "Musayev"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "narmin.shiriyeva@example.com",
                            FirstName = "Narmin",
                            GradeId = 4,
                            LastName = "Shiriyeva"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "javid.orujov@example.com",
                            FirstName = "Javid",
                            GradeId = 5,
                            LastName = "Orujov"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "konul.isgandarova@example.com",
                            FirstName = "Konul",
                            GradeId = 1,
                            LastName = "Isgandarova"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "fuad.bayramli@example.com",
                            FirstName = "Fuad",
                            GradeId = 2,
                            LastName = "Bayramli"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "sabina.huseynli@example.com",
                            FirstName = "Sabina",
                            GradeId = 3,
                            LastName = "Huseynli"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "elnur.veliyev@example.com",
                            FirstName = "Elnur",
                            GradeId = 4,
                            LastName = "Veliyev"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "amina.safarli@example.com",
                            FirstName = "Amina",
                            GradeId = 5,
                            LastName = "Safarli"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "tofig.guliyev@example.com",
                            FirstName = "Tofig",
                            GradeId = 1,
                            LastName = "Guliyev"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "lala.karimzade@example.com",
                            FirstName = "Lala",
                            GradeId = 5,
                            LastName = "Karimzade"
                        });
                });

            modelBuilder.Entity("OData_Learning.Entities.Student", b =>
                {
                    b.HasOne("OData_Learning.Entities.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("OData_Learning.Entities.Grade", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
